{
  desired_sr: 32000,
  window: True,
  OVERWRITE_EMBEDDINGS: True,
  embedding_path: C:\Users\hurh\Github\underwater-noise\data\embeddings,
  data_augment: MixUp,
  same_class: True,
  mix_perc: 0.5,
  mix_alpha: 0.1,
  mix_crop_length: 400,
  mix_batch_size: 32,
  grid_search_params: {
    "C": [1,1.5,2,2.5],
    "kernel": [
      "rbf"
    ],
    "gamma": [0.1,0.3],
    "probability": [true]
 }
  
}