{
 model_path: C:\Users\hurh\GitHub\underwater-noise\final_weights\VGGish\model.joblib,
 labels_mapping_path: C:\Users\hurh\GitHub\underwater-noise\final_weights\VGGish\labels_mapping.json,
 desired_sr: 32000,
 data_augment: None,
 duration: 1.0
}